name: Deploy Site

on:
  workflow_dispatch:

jobs:
  build:
    name: Build and Deploy site

    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [16]
        packager: [npm]

    runs-on: ${{ matrix.os }}

    permissions:
      contents: read
      pages: write
      id-token: write

    concurrency:
      group: pages
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v3
      - name: Set up Node
        id: setup
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: ${{ matrix.packager }}
      - name: Setup Pages
        uses: actions/configure-pages@v1
      - name: Install Dependencies
        run: npm ci
        if: steps.setup.outputs.cache-hit != true
      - name: Build Resources
        run: npm run build
      - name: Upload Static Artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './build/'
      - name: Deploy to Github Pages
        id: deploy
        uses: actions/deploy-pages@main
